# Generated by Django 3.0.6 on 2020-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_by', models.DateTimeField(auto_now=True)),
                ('updated_by', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
