# Generated by Django 3.0.6 on 2020-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.ManyToManyField(to='signal_demo_app.UserProfile')),
            ],
        ),
    ]
